Correct some indenting in includes and requires

diff --git a/bin/include b/bin/include
--- a/bin/include
+++ b/bin/include
@@ -34,24 +34,24 @@ sh_stack_add -2 "Entering 'include()' and processing ${#} found arg(s): '${*}'"
 
 # Ensure that SH_LIBPATH has some substance, otherwise why bother?
 if (( "${#SH_LIBPATH}" == 0 )); then
-sh_stack_dump
-printf -- 'include: %s\n' "SH_LIBPATH appears to be empty" >&2
-if [ -t 0 ]; then
-    return 1
-else
-    exit 1
-fi
+    sh_stack_dump
+    printf -- 'include: %s\n' "SH_LIBPATH appears to be empty" >&2
+    if [ -t 0 ]; then
+        return 1
+    else
+        exit 1
+    fi
 fi
 
 # Ensure that we have an arg to parse
 if (( "${#}" == 0 )); then
-sh_stack_dump
-printf -- 'include: %s\n' "No args given" >&2
-if [ -t 0 ]; then
-    return 1
-else
-    exit 1
-fi
+    sh_stack_dump
+    printf -- 'include: %s\n' "No args given" >&2
+    if [ -t 0 ]; then
+        return 1
+    else
+        exit 1
+    fi
 fi
 
 # Assign our target to a var
@@ -65,40 +65,40 @@ _is_lib_loaded "${_include_target}" && return 0
 # Example: include /opt/something/specific/library.sh
 sh_stack_add -2 "Is '${_include_target}' a full path to a file?"
 if [ -f "${_include_target}" ]; then
-sh_stack_add -3 "Full path: '${_include_target}' exists.  Is it readable?"
-if [ -r "${_include_target}" ]; then
-    sh_stack_add -4 "Full path: '${_include_target}' readable.  Loading."
-    # shellcheck disable=SC1090
-    if . "${_include_target}"; then
-    # Add the library to SH_LIBS_LOADED
-    SH_LIBS_LOADED="${SH_LIBS_LOADED} ${_include_target}"
-    # Strip the leading space char
-    SH_LIBS_LOADED="${SH_LIBS_LOADED# }"
-    export SH_LIBS_LOADED
-    unset -v _include_target
-    return 0
+    sh_stack_add -3 "Full path: '${_include_target}' exists.  Is it readable?"
+    if [ -r "${_include_target}" ]; then
+        sh_stack_add -4 "Full path: '${_include_target}' readable.  Loading."
+        # shellcheck disable=SC1090
+        if . "${_include_target}"; then
+            # Add the library to SH_LIBS_LOADED
+            SH_LIBS_LOADED="${SH_LIBS_LOADED} ${_include_target}"
+            # Strip the leading space char
+            SH_LIBS_LOADED="${SH_LIBS_LOADED# }"
+            export SH_LIBS_LOADED
+            unset -v _include_target
+            return 0
+        else
+            sh_stack_add -5 "Full path: '${_include_target}' readable but not loadable.  Failing."
+            sh_stack_dump
+            printf -- 'include: %s\n' "Error while includeing '${_include_target}'" >&2
+            unset -v _include_target
+            if [ -t 0 ]; then
+                return 1
+            else
+                exit 1
+            fi
+        fi
     else
-    sh_stack_add -5 "Full path: '${_include_target}' readable but not loadable.  Failing."
-    sh_stack_dump
-    printf -- 'include: %s\n' "Error while includeing '${_include_target}'" >&2
-    unset -v _include_target
-    if [ -t 0 ]; then
-        return 1
-    else
-        exit 1
+        sh_stack_add -4 "Full path: '${_include_target}' unreadable.  Failing."
+        sh_stack_dump
+        printf -- 'include: %s\n' "Insufficient permissions while includeing '${_include_target}'" >&2
+        unset -v _include_target
+        if [ -t 0 ]; then
+            return 1
+        else
+            exit 1
+        fi
     fi
-    fi
-else
-    sh_stack_add -4 "Full path: '${_include_target}' unreadable.  Failing."
-    sh_stack_dump
-    printf -- 'include: %s\n' "Insufficient permissions while includeing '${_include_target}'" >&2
-    unset -v _include_target
-    if [ -t 0 ]; then
-    return 1
-    else
-    exit 1
-    fi
-fi
 fi
 sh_stack_add -2 "'${_include_target}' is apparently not a full path to a file."
 
@@ -107,22 +107,78 @@ sh_stack_add -2 "'${_include_target}' is apparently not a full path to a file."
 # Is it a subdir/library with an explicit extension e.g. include text/puts.bash
 # Is it a subdir/library with an implicit extension (i.e. ".sh" default) e.g. include text/puts
 for _element in "${SH_LIBPATH_ARRAY[@]}"; do
-# Is the given target a subdir within $_element?  If so, load everything within that path.
-# Note: we only load everything with a .sh extension
-# We don't want to try loading library.zsh into bash, for example
-sh_stack_add -2 "Is '${_include_target}' a sub-directory within ${_element}?"
-if [ -d "${_element}/${_include_target}" ]; then
-    _subdir="${_element}/${_include_target}"
-    sh_stack_add -3 "Loading all libraries and functions from '${_subdir}'"
-    for _load_target in "${_subdir}"/*.sh; do
-    # Ensure that it's not already loaded
-    _is_lib_loaded "${_load_target}" && continue
-    if [ -r "${_load_target}" ]; then
+    # Is the given target a subdir within $_element?  If so, load everything within that path.
+    # Note: we only load everything with a .sh extension
+    # We don't want to try loading library.zsh into bash, for example
+    sh_stack_add -2 "Is '${_include_target}' a sub-directory within ${_element}?"
+    if [ -d "${_element}/${_include_target}" ]; then
+        _subdir="${_element}/${_include_target}"
+        sh_stack_add -3 "Loading all libraries and functions from '${_subdir}'"
+        for _load_target in "${_subdir}"/*.sh; do
+            # Ensure that it's not already loaded
+            _is_lib_loaded "${_load_target}" && continue
+            if [ -r "${_load_target}" ]; then
+                # shellcheck disable=SC1090
+                . "${_load_target}" || {
+                sh_stack_dump
+                printf -- 'include: %s\n' "Failed to load '${_load_target}'" >&2
+                unset -v _element _subdir _load_target _include_target
+                if  [ -t 0 ]; then
+                    return 1
+                else
+                    exit 1
+                fi
+                }
+                SH_LIBS_LOADED="${SH_LIBS_LOADED} ${_load_target}"
+                SH_LIBS_LOADED="${SH_LIBS_LOADED# }"
+                unset -v _element _subdir _load_target _include_target
+            else
+                sh_stack_dump
+                printf -- 'include: %s\n' "Insufficient permissions while includeing '${_load_target}'" >&2
+                unset -v _element _subdir _load_target _include_target
+                if  [ -t 0 ]; then
+                return 1
+                else
+                exit 1
+                fi
+            fi
+        done
+        export SH_LIBS_LOADED
+        unset -v _element _subdir _load_target _include_target
+        if  [ -t 0 ]; then
+            return 0
+        else
+            exit 0
+        fi
+    fi
+    sh_stack_add -2 "'${_include_target}' is apparently not a sub-directory within ${_element}."
+
+    # With the above scenario out of the way, we now assess the following in order:
+    # include subdir/library.extension (e.g. include text/tolower.sh)
+    #     This scenario allows us to load shell specific libs e.g. text/tolower.zsh
+    # include subdir/library           (e.g. include text/tolower)
+    #     This scenario defaults to the .sh extension i.e. text/tolower = text/tolower.sh
+    sh_stack_add -2 "Is '${_include_target}' a relative path within ${_element}?"
+    if [ -f "${_element}/${_include_target}" ]||[ -f "${_element}/${_include_target}.sh" ]; then
+        sh_stack_add -3 "Relative path: '${_element}/${_include_target}' exists.  Is it readable?"
+        if [ -r "${_element}/${_include_target}" ]; then
+            _load_target="${_element}/${_include_target}"
+        elif [ -r "${_element}/${_include_target}.sh" ]; then
+            _load_target="${_element}/${_include_target}.sh"
+        else
+            sh_stack_dump
+            printf -- 'include: %s\n' "Insufficient permissions while includeing '${_include_target}' from '${_element}'" >&2
+            unset -v _element _include_target
+            if  [ -t 0 ]; then
+                return 1
+            else
+                exit 1
+            fi
+        fi
+
         # shellcheck disable=SC1090
         . "${_load_target}" || {
-        sh_stack_dump
         printf -- 'include: %s\n' "Failed to load '${_load_target}'" >&2
-        unset -v _element _subdir _load_target _include_target
         if  [ -t 0 ]; then
             return 1
         else
@@ -131,67 +187,11 @@ if [ -d "${_element}/${_include_target}" ]; then
         }
         SH_LIBS_LOADED="${SH_LIBS_LOADED} ${_load_target}"
         SH_LIBS_LOADED="${SH_LIBS_LOADED# }"
-        unset -v _element _subdir _load_target _include_target
+        unset -v _element _include_target _load_target
+        return 0
     else
-        sh_stack_dump
-        printf -- 'include: %s\n' "Insufficient permissions while includeing '${_load_target}'" >&2
-        unset -v _element _subdir _load_target _include_target
-        if  [ -t 0 ]; then
-        return 1
-        else
-        exit 1
-        fi
+        sh_stack_add -2 "Is '${_include_target}' a relative path within ${_element}?"
     fi
-    done
-    export SH_LIBS_LOADED
-    unset -v _element _subdir _load_target _include_target
-    if  [ -t 0 ]; then
-    return 0
-    else
-    exit 0
-    fi
-fi
-sh_stack_add -2 "'${_include_target}' is apparently not a sub-directory within ${_element}."
-
-# With the above scenario out of the way, we now assess the following in order:
-# include subdir/library.extension (e.g. include text/tolower.sh)
-#     This scenario allows us to load shell specific libs e.g. text/tolower.zsh
-# include subdir/library           (e.g. include text/tolower)
-#     This scenario defaults to the .sh extension i.e. text/tolower = text/tolower.sh
-sh_stack_add -2 "Is '${_include_target}' a relative path within ${_element}?"
-if [ -f "${_element}/${_include_target}" ]||[ -f "${_element}/${_include_target}.sh" ]; then
-    sh_stack_add -3 "Relative path: '${_element}/${_include_target}' exists.  Is it readable?"
-    if [ -r "${_element}/${_include_target}" ]; then
-    _load_target="${_element}/${_include_target}"
-    elif [ -r "${_element}/${_include_target}.sh" ]; then
-    _load_target="${_element}/${_include_target}.sh"
-    else
-    sh_stack_dump
-    printf -- 'include: %s\n' "Insufficient permissions while includeing '${_include_target}' from '${_element}'" >&2
-    unset -v _element _include_target
-    if  [ -t 0 ]; then
-        return 1
-    else
-        exit 1
-    fi
-    fi
-
-    # shellcheck disable=SC1090
-    . "${_load_target}" || {
-    printf -- 'include: %s\n' "Failed to load '${_load_target}'" >&2
-    if  [ -t 0 ]; then
-        return 1
-    else
-        exit 1
-    fi
-    }
-    SH_LIBS_LOADED="${SH_LIBS_LOADED} ${_load_target}"
-    SH_LIBS_LOADED="${SH_LIBS_LOADED# }"
-    unset -v _element _include_target _load_target
-    return 0
-else
-    sh_stack_add -2 "Is '${_include_target}' a relative path within ${_element}?"
-fi
 done
 
 # If we're here, then 'include()' wasn't called correctly
@@ -199,7 +199,7 @@ sh_stack_dump
 printf -- 'include: %s\n' "Unspecified error while executing 'include ${*}'" >&2
 unset -v _subdir _function _subdir_path _include_target
 if  [ -t 0 ]; then
-return 1
+    return 1
 else
-exit 1
+    exit 1
 fi
diff --git a/bin/requires b/bin/requires
--- a/bin/requires
+++ b/bin/requires
@@ -20,64 +20,64 @@
 # requires curl sed awk /etc/someconf.cfg
 
 for _item in "${@}"; do
-# First, is this a variable check?
-# There has to be a cleaner/safer way to do this
-case "${_item}" in
-    (*=*)
-    _key="${_item%%=*}" # Everything left of the first '='
-    _val="${_item#*=}"  # Everything right of the first '='
-    eval [ \$"${_key}" = "${_val}" ] && continue
-    ;;
-    (BASH*)
-    # Shell version check e.g. 'requires BASH32' = we check for bash 3.2 or newer
-    # To strictly require a specific version, you could use the keyval test above
-    # TO-DO: Expand the "is greater than" logic, add extra shells
-    if [ "${#BASH_VERSION}" -gt 0 ]; then
-        # Get first three chars e.g. '4.3'
-        _bashver="${BASH_VERSION%${BASH_VERSION#???}}"
-        # Concat and remove dot e.g. 'BASH43'
-        _bashver="BASH${_bashver/./}"
-        # Test on string (e.g. BASH44 = BASH44)
-        [ "${1}" = "${_bashver}" ] && continue
-        # Test on integer by stripping "BASH" (e.g. 51 -ge 44)
-        [ "${1/BASH/}" -ge "${_bashver/BASH/}" ] && continue
-    fi
-    ;;
-    (KSH)
-    # At present we just check that we have one of the following env vars
-    [ "${#KSH_VERSION}" -gt 0 ] && continue
-    [ "${#.sh.version}" -gt 0 ] && continue
-    ;;
-    (ZSH*)
-    if [ "${#ZSH_VERSION}" -gt 0 ]; then
-        # ZSH_VERSION outputs a semantic number e.g. 5.7.1
-        # We use parameter expansion to pull out the dots e.g. ZSH571
-        # We do a string, then an int comparison just as with bash
-        [ "${1}" = "ZSH${ZSH_VERSION//./}" ] && continue
-        [ "${1/ZSH/}" -ge "${ZSH_VERSION//./}" ] && continue
-    fi
-    ;;
-    (root)
-    [ "${EUID:-$(id -u)}" -eq "0" ] && continue
-    ;;
-esac
+    # First, is this a variable check?
+    # There has to be a cleaner/safer way to do this
+    case "${_item}" in
+        (*=*)
+        _key="${_item%%=*}" # Everything left of the first '='
+        _val="${_item#*=}"  # Everything right of the first '='
+        eval [ \$"${_key}" = "${_val}" ] && continue
+        ;;
+        (BASH*)
+        # Shell version check e.g. 'requires BASH32' = we check for bash 3.2 or newer
+        # To strictly require a specific version, you could use the keyval test above
+        # TO-DO: Expand the "is greater than" logic, add extra shells
+        if [ "${#BASH_VERSION}" -gt 0 ]; then
+            # Get first three chars e.g. '4.3'
+            _bashver="${BASH_VERSION%${BASH_VERSION#???}}"
+            # Concat and remove dot e.g. 'BASH43'
+            _bashver="BASH${_bashver/./}"
+            # Test on string (e.g. BASH44 = BASH44)
+            [ "${1}" = "${_bashver}" ] && continue
+            # Test on integer by stripping "BASH" (e.g. 51 -ge 44)
+            [ "${1/BASH/}" -ge "${_bashver/BASH/}" ] && continue
+        fi
+        ;;
+        (KSH)
+        # At present we just check that we have one of the following env vars
+        [ "${#KSH_VERSION}" -gt 0 ] && continue
+        [ "${#.sh.version}" -gt 0 ] && continue
+        ;;
+        (ZSH*)
+        if [ "${#ZSH_VERSION}" -gt 0 ]; then
+            # ZSH_VERSION outputs a semantic number e.g. 5.7.1
+            # We use parameter expansion to pull out the dots e.g. ZSH571
+            # We do a string, then an int comparison just as with bash
+            [ "${1}" = "ZSH${ZSH_VERSION//./}" ] && continue
+            [ "${1/ZSH/}" -ge "${ZSH_VERSION//./}" ] && continue
+        fi
+        ;;
+        (root)
+        [ "${EUID:-$(id -u)}" -eq "0" ] && continue
+        ;;
+    esac
 
-# Next, try to determine if it's a command
-command -v "${_item}" >/dev/null 2>&1 && continue
+    # Next, try to determine if it's a command
+    command -v "${_item}" >/dev/null 2>&1 && continue
 
-# Next, see if it's an executable file e.g. a script to call
-[ -x ./"${_item}" ] && continue
+    # Next, see if it's an executable file e.g. a script to call
+    [ -x ./"${_item}" ] && continue
 
-# Next, let's see if it's a library in SH_LIBPATH
-for _target_lib in ${SH_LIBPATH//://$_item }/${_item}; do
-    [ -r "${_target_lib}" ] && continue
-done
+    # Next, let's see if it's a library in SH_LIBPATH
+    for _target_lib in ${SH_LIBPATH//://$_item }/${_item}; do
+        [ -r "${_target_lib}" ] && continue
+    done
 
-# Next, let's see if it's a readable file e.g. a cfg file to load
-[ -r "${_item}" ] && continue
+    # Next, let's see if it's a readable file e.g. a cfg file to load
+    [ -r "${_item}" ] && continue
 
-# If we get to this point, add it to our list of failures
-_failures="${_failures} ${_item}"
+    # If we get to this point, add it to our list of failures
+    _failures="${_failures} ${_item}"
 done
 
 # Strip any leading space from the construction of _failures
@@ -85,15 +85,15 @@ _failures="${_failures# }"
 
 # If we have no failures, then no news is good news - return quietly
 if [ "${#_failures}" -eq "0" ]; then
-unset -v _item _failures _target_lib _bashver
-return 0
-# Otherwise, we error out and exit immediately
+    unset -v _item _failures _target_lib _bashver
+    return 0
+    # Otherwise, we error out and exit immediately
 else
-printf -- '%s\n' "The following requirements were not met:" "${_failures}" >&2
-unset -v _item _failures _target_lib _bashver
-if [ -t 0 ]; then
-    return 1
-else
-    exit 1
-fi
+    printf -- '%s\n' "The following requirements were not met:" "${_failures}" >&2
+    unset -v _item _failures _target_lib _bashver
+    if [ -t 0 ]; then
+        return 1
+    else
+        exit 1
+    fi
 fi
